---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: docker.io/opensuse/leap:15.1
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: false
  # - name: instance1
    # image: registry.suse.com/suse/sle15:15.1
    # command: /sbin/init
    # tmpfs:
      # - /run
      # - /tmp
    # volumes:
      # - /sys/fs/cgroup:/sys/fs/cgroup:ro
    # pre_build_image: false
provisioner:
  name: ansible
  inventory:
    host_vars:
      instance:
        ansible_python_interpreter: /usr/bin/python3
        nagios_ver: 4.4.6
        nagios_sha: b1c6fb447f14995ea691941edd928ff4532b9e240e5058bac58b14eec14ceca1
verifier:
  name: ansible
